# For available configuration options, see:
#   https://github.com/testdouble/standard
ruby_version: 2.6

ignore:
  - 'Gemfile':
    - Layout/ExtraSpacing
  - 'app/**':
    - Layout/ExtraSpacing
  - 'spec/**':
    - Layout/ExtraSpacing
  - 'lambda_function.rb':
    - Style/GlobalVars
    - Layout/ArgumentAlignment
